@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 15 21:08:58 +0100 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_ff_rst_behav -key {Behavioral:sim_1:Functional:tb_ff_rst} -tclbatch tb_ff_rst.tcl -view C:/Users/Dominik Caban/OneDrive/FEKT VUT BRNO/DE1/GIT/digital-electronics-1/labs/05-ffs/vivado/flip_flops/tb_ff_rst_behav.wcfg -log simulate.log"
call xsim  tb_ff_rst_behav -key {Behavioral:sim_1:Functional:tb_ff_rst} -tclbatch tb_ff_rst.tcl -view C:/Users/Dominik Caban/OneDrive/FEKT VUT BRNO/DE1/GIT/digital-electronics-1/labs/05-ffs/vivado/flip_flops/tb_ff_rst_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
